### ISSUE TITLE
Argo Notifications Engine support

### ISSUE THREAD

**Issue by rbreeze** [argoproj-labs/argocd-extensions#1]
The Argo [Notifications Engine](https://github.com/argoproj/notifications-engine) makes it easy to add notifications support for K8S controllers. 

It would be great if Argo CD Extensions used Notifications Engine to make this even easier by allowing Extensions administrators to configure notifications directly in the `ArgoCDExtension` CR: 

```
apiVersion: v1
kind: ArgoCDExtension
metadata:
  name: rollout-extension
spec:
  repository: https://github.com/argoproj-labs/argocd-extensions-library
  revision: HEAD
  path: rollout
  notifications:
    configMap: argocd-notifications-cm
```

Using Notifications Engine, it may also be possible to allow configuration of notifications for Extended resources in the UI.
